### ISSUE TITLE
Upstream Linux perf tools not building with latest toolchain

### ISSUE THREAD

**Issue by acmel** [foss-for-synopsys-dwc-arc-processors/toolchain#137]
Using https://github.com/foss-for-synopsys-dwc-arc-processors/toolchain/releases/download/arc-2017.09-rc1/arc_gnu_2017.09-rc1_prebuilt_uclibc_le_arc700_linux_install.tar.gz

And trying to build tools/perf in the upstream kernel sources produces the messages below, this was working before as I routinely use a container (Dockerfile available at: http://vger.kernel.org/~acme/perf/fedora:24-x-ARC-uClibc-Dockerfile) to build it, IIRC the last toolchain that worked was: arc_gnu_2016.03_prebuilt_uclibc_le_archs_linux_install, the script that fetches the perf detached tarball (extracted from the kernel sources via 'make  perf-tarxz-src-pkg) and then cross builds it is at http://vger.kernel.org/~acme/perf/rx_and_build.sh

  builtin-sched.c: In function 'timehist_sched_switch_event':
  builtin-sched.c:2580:1: internal compiler error: in change_address_1, at emit-rtl.c:2150
   }
   ^
  util/db-export.c: In function 'db_export__sample':
  util/db-export.c:429:1: internal compiler error: in change_address_1, at emit-rtl.c:2150
   }
   ^
  Please submit a full bug report,
  with preprocessed source if appropriate.
  See <https://github.com/foss-for-synopsys-dwc-arc-processors/toolchain/issues> for instructions.

**Comment by fbedard** [comment]
Hi - just a note that we've reproduced the issue and are planning to fix it in the upcoming RC2 build!

Thanks for reporting.

**Comment by EvgeniiDidin** [comment]
Hi. This issue is fixed in arc-gnu-2017.09-eng010 toolchain build. 
I suggest to close this issue.

**Comment by fbedard** [comment]
Thanks Evgenii.  Let's close it when we have published RC2 (final RC) of GNU 2017.09 release, expected by end of the week.

**Comment by acmel** [comment]
Em Tue, Oct 17, 2017 at 10:32:25AM -0700, EvgeniiDidin escreveu:
> Hi. This issue is fixed in arc-gnu-2017.09-eng010 toolchain build. 
> I suggest to close this issue.

Where can I find such prebuilt toolchain to test?

- Arnaldo

**Comment by fbedard** [comment]
Hi Arnaldo, 

RC2 is now release at https://github.com/foss-for-synopsys-dwc-arc-processors/toolchain/releases/tag/arc-2017.09-rc2 

You can use prebuilts from there to verify that your issue has been fixed.   Please re-open if problem persists!

Thanks.
